# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'doctor.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1144, 730)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(30, 30, 1022, 670))
        self.frame_2.setStyleSheet("#frame_2{\n"
"    border-radius:22px;\n"
"    background-color: rgb(16, 18, 31);\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        self.frame_4.setGeometry(QtCore.QRect(300, 330, 120, 80))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.layoutWidget = QtWidgets.QWidget(self.frame_2)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 1021, 671))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.layoutWidget)
        self.frame.setStyleSheet("#frame{\n"
"    border-top-left-radius:22px;\n"
"    border-top-right-radius:22px;\n"
"    background-color:rgb(38,43,75);\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(10, -20, 81, 81))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("icons/logo.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.layoutWidget1 = QtWidgets.QWidget(self.frame)
        self.layoutWidget1.setGeometry(QtCore.QRect(100, 10, 266, 26))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_2 = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"    color:white;\n"
"    font-weight:bold;\n"
"    font-family:\"微软雅黑\";\n"
"    background-color:transparent;\n"
"    font-size:12px;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: rgba(211, 211, 211, 50%);\n"
"border-radius: 5px;\n"
"}\n"
"QPushButton:pressed {\n"
"\n"
"border-width: 1px;\n"
"padding-top: 4px;\n"
"padding-left: 4px;\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/一键诊断.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_3.setStyleSheet("QPushButton{\n"
"    color:white;\n"
"    font-weight:bold;\n"
"    font-family:\"微软雅黑\";\n"
"    background-color:transparent;\n"
"    font-size:12px;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: rgba(211, 211, 211, 50%);\n"
"border-radius: 5px;\n"
"}\n"
"QPushButton:pressed {\n"
"\n"
"border-width: 1px;\n"
"padding-top: 4px;\n"
"padding-left: 4px;\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/查看历史.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon1)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.pushButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton.setStyleSheet("QPushButton{\n"
"    color:white;\n"
"    font-weight:bold;\n"
"    font-family:\"微软雅黑\";\n"
"    background-color:transparent;\n"
"    font-size:12px;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: rgba(211, 211, 211, 50%);\n"
"border-radius: 5px;\n"
"}\n"
"QPushButton:pressed {\n"
"\n"
"border-width: 1px;\n"
"padding-top: 4px;\n"
"padding-left: 4px;\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/查看报告.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon2)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_4 = QtWidgets.QPushButton(self.frame)
        self.pushButton_4.setGeometry(QtCore.QRect(940, 10, 75, 23))
        self.pushButton_4.setStyleSheet("QPushButton{\n"
"    color:white;\n"
"    font-weight:bold;\n"
"    font-family:\"微软雅黑\";\n"
"    background-color:transparent;\n"
"    font-size:12px;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: rgba(211, 211, 211, 50%);\n"
"border-radius: 5px;\n"
"}\n"
"QPushButton:pressed {\n"
"\n"
"border-width: 1px;\n"
"padding-top: 4px;\n"
"padding-left: 4px;\n"
"}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/按钮_关闭.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon3)
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout.addWidget(self.frame)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_3 = QtWidgets.QFrame(self.layoutWidget)
        self.frame_3.setStyleSheet("#frame_3{\n"
"    border-bottom-left-radius:22px;\n"
"    \n"
"    background-color:rgb(16,18,31);\n"
"}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.frame_7 = QtWidgets.QFrame(self.frame_3)
        self.frame_7.setGeometry(QtCore.QRect(0, 40, 131, 321))
        self.frame_7.setStyleSheet("background-color:rgb(16,18,31);")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_7)
        self.pushButton_5.setStyleSheet("QPushButton{\n"
"    color:white;\n"
"    font-weight:bold;\n"
"    font-family:\"微软雅黑\";\n"
"    background-color:transparent;\n"
"    font-size:16px;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: rgba(211, 211, 211, 50%);\n"
"border-radius: 5px;\n"
"}\n"
"QPushButton:pressed {\n"
"\n"
"border-width: 1px;\n"
"padding-top: 4px;\n"
"padding-left: 4px;\n"
"}")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icons/加载模型.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_5.setIcon(icon4)
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_2.addWidget(self.pushButton_5)
        self.pushButton_6 = QtWidgets.QPushButton(self.frame_7)
        self.pushButton_6.setStyleSheet("QPushButton{\n"
"    color:white;\n"
"    font-weight:bold;\n"
"    font-family:\"微软雅黑\";\n"
"    background-color:transparent;\n"
"    font-size:16px;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: rgba(211, 211, 211, 50%);\n"
"border-radius: 5px;\n"
"}\n"
"QPushButton:pressed {\n"
"\n"
"border-width: 1px;\n"
"padding-top: 4px;\n"
"padding-left: 4px;\n"
"}")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("icons/选择影像.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_6.setIcon(icon5)
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout_2.addWidget(self.pushButton_6)
        self.pushButton_9 = QtWidgets.QPushButton(self.frame_7)
        self.pushButton_9.setStyleSheet("QPushButton{\n"
"    color:white;\n"
"    font-weight:bold;\n"
"    font-family:\"微软雅黑\";\n"
"    background-color:transparent;\n"
"    font-size:16px;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: rgba(211, 211, 211, 50%);\n"
"border-radius: 5px;\n"
"}\n"
"QPushButton:pressed {\n"
"\n"
"border-width: 1px;\n"
"padding-top: 4px;\n"
"padding-left: 4px;\n"
"}")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("icons/开始推理.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_9.setIcon(icon6)
        self.pushButton_9.setObjectName("pushButton_9")
        self.verticalLayout_2.addWidget(self.pushButton_9)
        self.pushButton_10 = QtWidgets.QPushButton(self.frame_7)
        self.pushButton_10.setStyleSheet("QPushButton{\n"
"    color:white;\n"
"    font-weight:bold;\n"
"    font-family:\"微软雅黑\";\n"
"    background-color:transparent;\n"
"    font-size:16px;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: rgba(211, 211, 211, 50%);\n"
"border-radius: 5px;\n"
"}\n"
"QPushButton:pressed {\n"
"\n"
"border-width: 1px;\n"
"padding-top: 4px;\n"
"padding-left: 4px;\n"
"}")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("icons/患者信息.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_10.setIcon(icon7)
        self.pushButton_10.setObjectName("pushButton_10")
        self.verticalLayout_2.addWidget(self.pushButton_10)
        self.pushButton_11 = QtWidgets.QPushButton(self.frame_7)
        self.pushButton_11.setStyleSheet("QPushButton{\n"
"    color:white;\n"
"    font-weight:bold;\n"
"    font-family:\"微软雅黑\";\n"
"    background-color:transparent;\n"
"    font-size:16px;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: rgba(211, 211, 211, 50%);\n"
"border-radius: 5px;\n"
"}\n"
"QPushButton:pressed {\n"
"\n"
"border-width: 1px;\n"
"padding-top: 4px;\n"
"padding-left: 4px;\n"
"}")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("icons/诊断报告.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_11.setIcon(icon8)
        self.pushButton_11.setObjectName("pushButton_11")
        self.verticalLayout_2.addWidget(self.pushButton_11)
        self.horizontalLayout_2.addWidget(self.frame_3)
        self.frame_5 = QtWidgets.QFrame(self.layoutWidget)
        self.frame_5.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.frame_10 = QtWidgets.QFrame(self.frame_5)
        self.frame_10.setGeometry(QtCore.QRect(-1, 610, 641, 16))
        self.frame_10.setStyleSheet("#frame_10{\n"
"    \n"
"    height:5px;\n"
"    background-color:rgb(16,18,31);\n"
"}")
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.layoutWidget2 = QtWidgets.QWidget(self.frame_5)
        self.layoutWidget2.setGeometry(QtCore.QRect(0, 0, 631, 601))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_8 = QtWidgets.QFrame(self.layoutWidget2)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.layoutWidget3 = QtWidgets.QWidget(self.frame_8)
        self.layoutWidget3.setGeometry(QtCore.QRect(20, 10, 191, 271))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_4.setStyleSheet("QLabel{\n"
"    font-family:\"微软雅黑\";\n"
"    font-size:16px;\n"
"    font-weight:bold;\n"
"    \n"
"}")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.spinBox_2 = QtWidgets.QSpinBox(self.layoutWidget3)
        self.spinBox_2.setStyleSheet("QSpinBox {\n"
"    \n"
"\n"
"    \n"
"    font-family:\"微软雅黑\";\n"
"    font-weight:bold;\n"
"    background-color: white;\n"
"    border-radius: 5px;\n"
"    padding: 2px;\n"
"    height:30px;\n"
"    width:10px;\n"
"}\n"
"\n"
"QSpinBox:hover {\n"
"    border: 2px solid lightgray;\n"
"    border-radius: 5px;\n"
"}\n"
"QSpinBox::up-button {\n"
"    border: 0px;\n"
"}\n"
"\n"
"QSpinBox::down-button {\n"
"    border: 0px;\n"
"}\n"
"\n"
"\n"
"QSpinBox::up-arrow{\n"
"    width: 10px;\n"
"    height: 10px;\n"
"    image: url(:/新前缀/up_arrow.png);\n"
"}\n"
"QSpinBox::down-arrow {\n"
"    width: 10px;\n"
"    height: 10px;\n"
"    image: url(:/新前缀/down_arrow.png);\n"
"}")
        self.spinBox_2.setObjectName("spinBox_2")
        self.horizontalLayout_3.addWidget(self.spinBox_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_8 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_8.setStyleSheet("QLabel{\n"
"    font-family:\"微软雅黑\";\n"
"    font-size:16px;\n"
"    font-weight:bold;\n"
"    \n"
"}")
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_5.addWidget(self.label_8)
        self.comboBox_5 = QtWidgets.QComboBox(self.layoutWidget3)
        self.comboBox_5.setStyleSheet("QComboBox {\n"
"    font-family:\"微软雅黑\";\n"
"    font-weight:bold;\n"
"    background-color: white;\n"
"    border-radius: 5px;\n"
"    padding: 2px;\n"
"    height:30px;\n"
"    width:10px;\n"
"}\n"
"QComboBox::drop-down {\n"
"    border: none;\n"
"}\n"
"\n"
"QComboBox:hover {\n"
"    border: 2px solid lightgray;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    width: 10px;\n"
"    height: 10px;\n"
"    image: url(:/新前缀/down_arrow.png);\n"
"}\n"
"")
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.horizontalLayout_5.addWidget(self.comboBox_5)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.cb_wwwc = QtWidgets.QComboBox(self.layoutWidget3)
        self.cb_wwwc.setStyleSheet("QComboBox {\n"
"    font-family:\"微软雅黑\";\n"
"    font-weight:bold;\n"
"    background-color: white;\n"
"    border-radius: 5px;\n"
"    padding: 2px;\n"
"    height:40px;\n"
"}\n"
"QComboBox::drop-down {\n"
"    border: none;\n"
"}\n"
"\n"
"QComboBox:hover {\n"
"    border: 2px solid lightgray;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    width: 10px;\n"
"    height: 10px;\n"
"    image: url(:/新前缀/down_arrow.png);\n"
"}\n"
"")
        self.cb_wwwc.setObjectName("cb_wwwc")
        self.cb_wwwc.addItem("")
        self.cb_wwwc.addItem("")
        self.cb_wwwc.addItem("")
        self.cb_wwwc.addItem("")
        self.cb_wwwc.addItem("")
        self.verticalLayout_3.addWidget(self.cb_wwwc)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_9 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_9.setStyleSheet("QLabel{\n"
"    font-family:\"微软雅黑\";\n"
"    font-size:16px;\n"
"    font-weight:bold;\n"
"    \n"
"}")
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_6.addWidget(self.label_9)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.line_ww = QtWidgets.QLineEdit(self.layoutWidget3)
        self.line_ww.setStyleSheet("QLineEdit {\n"
"    font-family:\"微软雅黑\";\n"
"    font-weight:bold;\n"
"    background-color: white;\n"
"    border-radius: 5px;\n"
"    padding: 2px;\n"
"    height:30px;\n"
"}")
        self.line_ww.setObjectName("line_ww")
        self.horizontalLayout_6.addWidget(self.line_ww)
        self.horizontalLayout_6.setStretch(0, 1)
        self.horizontalLayout_6.setStretch(1, 2)
        self.horizontalLayout_6.setStretch(2, 4)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.slider_ww = QtWidgets.QSlider(self.layoutWidget3)
        self.slider_ww.setOrientation(QtCore.Qt.Horizontal)
        self.slider_ww.setObjectName("slider_ww")
        self.verticalLayout_3.addWidget(self.slider_ww)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_10 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_10.setStyleSheet("QLabel{\n"
"    font-family:\"微软雅黑\";\n"
"    font-size:16px;\n"
"    font-weight:bold;\n"
"    \n"
"}")
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_7.addWidget(self.label_10)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem1)
        self.line_wc = QtWidgets.QLineEdit(self.layoutWidget3)
        self.line_wc.setStyleSheet("QLineEdit {\n"
"    font-family:\"微软雅黑\";\n"
"    font-weight:bold;\n"
"    background-color: white;\n"
"    border-radius: 5px;\n"
"    padding: 2px;\n"
"    height:30px;\n"
"}")
        self.line_wc.setObjectName("line_wc")
        self.horizontalLayout_7.addWidget(self.line_wc)
        self.horizontalLayout_7.setStretch(0, 1)
        self.horizontalLayout_7.setStretch(1, 2)
        self.horizontalLayout_7.setStretch(2, 4)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.slider_wc = QtWidgets.QSlider(self.layoutWidget3)
        self.slider_wc.setOrientation(QtCore.Qt.Horizontal)
        self.slider_wc.setObjectName("slider_wc")
        self.verticalLayout_3.addWidget(self.slider_wc)
        self.verticalLayout_5.addWidget(self.frame_8)
        self.frame_9 = QtWidgets.QFrame(self.layoutWidget2)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.layoutWidget4 = QtWidgets.QWidget(self.frame_9)
        self.layoutWidget4.setGeometry(QtCore.QRect(10, -50, 201, 341))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem2)
        self.label_11 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_11.setStyleSheet("QLabel{\n"
"    font-family:\"微软雅黑\";\n"
"    font-size:16px;\n"
"    font-weight:bold;\n"
"    \n"
"}")
        self.label_11.setObjectName("label_11")
        self.verticalLayout_4.addWidget(self.label_11)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.listWidget = QtWidgets.QListWidget(self.layoutWidget4)
        self.listWidget.setStyleSheet("QListWidget {\n"
"    font-family:\"微软雅黑\";\n"
"    font-weight:bold;\n"
"    background-color: white;\n"
"    border-radius: 5px;\n"
"    padding: 2px;\n"
"    height:40px;\n"
"}")
        self.listWidget.setObjectName("listWidget")
        self.horizontalLayout_4.addWidget(self.listWidget)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.horizontalLayout_4.setStretch(0, 1)
        self.horizontalLayout_4.setStretch(1, 3)
        self.horizontalLayout_4.setStretch(2, 1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.verticalLayout_4.setStretch(0, 1)
        self.verticalLayout_4.setStretch(2, 3)
        self.verticalLayout_5.addWidget(self.frame_9)
        self.verticalLayout_5.setStretch(0, 2)
        self.verticalLayout_5.setStretch(1, 2)
        self.horizontalLayout_8.addLayout(self.verticalLayout_5)
        self.canvas = QtWidgets.QLabel(self.layoutWidget2)
        self.canvas.setStyleSheet("QLabel {\n"
"    font-family:\"微软雅黑\";\n"
"    font-weight:bold;\n"
"    background-color: white;\n"
"    border-radius: 5px;\n"
"    padding: 2px;\n"
"    height:40px;\n"
"}")
        self.canvas.setText("")
        self.canvas.setObjectName("canvas")
        self.horizontalLayout_8.addWidget(self.canvas)
        self.horizontalLayout_2.addWidget(self.frame_5)
        self.frame_6 = QtWidgets.QFrame(self.layoutWidget)
        self.frame_6.setStyleSheet("#frame_6{\n"
"    border-bottom-right-radius:22px;\n"
"    \n"
"    /*background-color:rgb(32,33,35);*/\n"
"    background-color:rgb(16,18,31);\n"
"}")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.frame_11 = QtWidgets.QFrame(self.frame_6)
        self.frame_11.setGeometry(QtCore.QRect(-1, 5, 261, 31))
        self.frame_11.setStyleSheet("background-color:rgb(38,45,75);")
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.label_3 = QtWidgets.QLabel(self.frame_11)
        self.label_3.setGeometry(QtCore.QRect(10, 0, 91, 31))
        self.label_3.setStyleSheet("#label_3{\n"
"    font-size:16px;\n"
"    font-family:\"微软雅黑\";\n"
"    font-weight:bold;\n"
"    color:white;\n"
"}")
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(self.frame_6)
        self.label_5.setGeometry(QtCore.QRect(40, 50, 51, 21))
        self.label_5.setStyleSheet("QLabel{\n"
"    font-size:15px;\n"
"    font-family:\"微软雅黑\";\n"
"    font-weight:bold;\n"
"    color:white;\n"
"}")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frame_6)
        self.label_6.setGeometry(QtCore.QRect(40, 170, 211, 16))
        self.label_6.setStyleSheet("QLabel{\n"
"    font-size:13px;\n"
"    font-family:\"微软雅黑\";\n"
"    font-weight:bold;\n"
"\n"
"    color:rgb(206, 206, 206);\n"
"}")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.frame_6)
        self.label_7.setGeometry(QtCore.QRect(40, 140, 51, 21))
        self.label_7.setStyleSheet("QLabel{\n"
"    font-size:15px;\n"
"    font-family:\"微软雅黑\";\n"
"    font-weight:bold;\n"
"    color:white;\n"
"}")
        self.label_7.setObjectName("label_7")
        self.label_12 = QtWidgets.QLabel(self.frame_6)
        self.label_12.setGeometry(QtCore.QRect(40, 230, 211, 16))
        self.label_12.setStyleSheet("QLabel{\n"
"    font-size:13px;\n"
"    font-family:\"微软雅黑\";\n"
"    font-weight:bold;\n"
"\n"
"    color:rgb(206, 206, 206);\n"
"}")
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.frame_6)
        self.label_13.setGeometry(QtCore.QRect(40, 200, 51, 21))
        self.label_13.setStyleSheet("QLabel{\n"
"    font-size:15px;\n"
"    font-family:\"微软雅黑\";\n"
"    font-weight:bold;\n"
"    color:white;\n"
"}")
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.frame_6)
        self.label_14.setGeometry(QtCore.QRect(40, 290, 211, 16))
        self.label_14.setStyleSheet("QLabel{\n"
"    font-size:13px;\n"
"    font-family:\"微软雅黑\";\n"
"    font-weight:bold;\n"
"\n"
"    color:rgb(206, 206, 206);\n"
"}")
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.frame_6)
        self.label_15.setGeometry(QtCore.QRect(40, 260, 51, 21))
        self.label_15.setStyleSheet("QLabel{\n"
"    font-size:15px;\n"
"    font-family:\"微软雅黑\";\n"
"    font-weight:bold;\n"
"    color:white;\n"
"}")
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.frame_6)
        self.label_16.setGeometry(QtCore.QRect(40, 350, 211, 16))
        self.label_16.setStyleSheet("QLabel{\n"
"    font-size:13px;\n"
"    font-family:\"微软雅黑\";\n"
"    font-weight:bold;\n"
"\n"
"    color:rgb(206, 206, 206);\n"
"}")
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.frame_6)
        self.label_17.setGeometry(QtCore.QRect(40, 320, 51, 21))
        self.label_17.setStyleSheet("QLabel{\n"
"    font-size:15px;\n"
"    font-family:\"微软雅黑\";\n"
"    font-weight:bold;\n"
"    color:white;\n"
"}")
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.frame_6)
        self.label_18.setGeometry(QtCore.QRect(40, 80, 211, 51))
        self.label_18.setStyleSheet("QLabel{\n"
"    font-size:13px;\n"
"    font-family:\"微软雅黑\";\n"
"    font-weight:bold;\n"
"\n"
"    color:rgb(206, 206, 206);\n"
"}")
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.frame_6)
        self.label_19.setGeometry(QtCore.QRect(40, 380, 51, 21))
        self.label_19.setStyleSheet("QLabel{\n"
"    font-size:15px;\n"
"    font-family:\"微软雅黑\";\n"
"    font-weight:bold;\n"
"    color:white;\n"
"}")
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.frame_6)
        self.label_20.setGeometry(QtCore.QRect(40, 410, 211, 16))
        self.label_20.setStyleSheet("QLabel{\n"
"    font-size:13px;\n"
"    font-family:\"微软雅黑\";\n"
"    font-weight:bold;\n"
"\n"
"    color:rgb(206, 206, 206);\n"
"}")
        self.label_20.setObjectName("label_20")
        self.frame_12 = QtWidgets.QFrame(self.frame_6)
        self.frame_12.setGeometry(QtCore.QRect(0, 49, 41, 241))
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.label_22 = QtWidgets.QLabel(self.frame_12)
        self.label_22.setGeometry(QtCore.QRect(10, 0, 21, 31))
        self.label_22.setStyleSheet("")
        self.label_22.setText("")
        self.label_22.setPixmap(QtGui.QPixmap("icons/流程图1.png"))
        self.label_22.setScaledContents(True)
        self.label_22.setObjectName("label_22")
        self.label_21 = QtWidgets.QLabel(self.frame_12)
        self.label_21.setGeometry(QtCore.QRect(0, 10, 41, 91))
        self.label_21.setStyleSheet("")
        self.label_21.setText("")
        self.label_21.setPixmap(QtGui.QPixmap("icons/流程图2.png"))
        self.label_21.setScaledContents(True)
        self.label_21.setObjectName("label_21")
        self.label_23 = QtWidgets.QLabel(self.frame_12)
        self.label_23.setGeometry(QtCore.QRect(10, 80, 21, 31))
        self.label_23.setStyleSheet("")
        self.label_23.setText("")
        self.label_23.setPixmap(QtGui.QPixmap("icons/流程图1.png"))
        self.label_23.setScaledContents(True)
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.frame_6)
        self.label_24.setGeometry(QtCore.QRect(0, 140, 41, 81))
        self.label_24.setStyleSheet("")
        self.label_24.setText("")
        self.label_24.setPixmap(QtGui.QPixmap("icons/流程图2.png"))
        self.label_24.setScaledContents(True)
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.frame_6)
        self.label_25.setGeometry(QtCore.QRect(10, 200, 21, 31))
        self.label_25.setStyleSheet("")
        self.label_25.setText("")
        self.label_25.setPixmap(QtGui.QPixmap("icons/流程图1.png"))
        self.label_25.setScaledContents(True)
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.frame_6)
        self.label_26.setGeometry(QtCore.QRect(0, 190, 41, 81))
        self.label_26.setStyleSheet("")
        self.label_26.setText("")
        self.label_26.setPixmap(QtGui.QPixmap("icons/流程图2.png"))
        self.label_26.setScaledContents(True)
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.frame_6)
        self.label_27.setGeometry(QtCore.QRect(10, 260, 21, 31))
        self.label_27.setStyleSheet("")
        self.label_27.setText("")
        self.label_27.setPixmap(QtGui.QPixmap("icons/流程图1.png"))
        self.label_27.setScaledContents(True)
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.frame_6)
        self.label_28.setGeometry(QtCore.QRect(0, 260, 41, 81))
        self.label_28.setStyleSheet("、")
        self.label_28.setText("")
        self.label_28.setPixmap(QtGui.QPixmap("icons/流程图2.png"))
        self.label_28.setScaledContents(True)
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(self.frame_6)
        self.label_29.setGeometry(QtCore.QRect(10, 320, 21, 31))
        self.label_29.setStyleSheet("")
        self.label_29.setText("")
        self.label_29.setPixmap(QtGui.QPixmap("icons/流程图1.png"))
        self.label_29.setScaledContents(True)
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.frame_6)
        self.label_30.setGeometry(QtCore.QRect(0, 310, 41, 81))
        self.label_30.setStyleSheet("")
        self.label_30.setText("")
        self.label_30.setPixmap(QtGui.QPixmap("icons/流程图2.png"))
        self.label_30.setScaledContents(True)
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(self.frame_6)
        self.label_31.setGeometry(QtCore.QRect(10, 380, 21, 31))
        self.label_31.setStyleSheet("")
        self.label_31.setText("")
        self.label_31.setPixmap(QtGui.QPixmap("icons/流程图1.png"))
        self.label_31.setScaledContents(True)
        self.label_31.setObjectName("label_31")
        self.horizontalLayout_2.addWidget(self.frame_6)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 5)
        self.horizontalLayout_2.setStretch(2, 2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 14)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_2.setText(_translate("MainWindow", "一键诊断"))
        self.pushButton_3.setText(_translate("MainWindow", "查看历史"))
        self.pushButton.setText(_translate("MainWindow", "查看诊断报告"))
        self.pushButton_4.setText(_translate("MainWindow", "退出"))
        self.pushButton_5.setText(_translate("MainWindow", "加载模型"))
        self.pushButton_6.setText(_translate("MainWindow", "选择影像"))
        self.pushButton_9.setText(_translate("MainWindow", "开始推理"))
        self.pushButton_10.setText(_translate("MainWindow", "患者信息"))
        self.pushButton_11.setText(_translate("MainWindow", "诊断报告"))
        self.label_4.setText(_translate("MainWindow", "类别数量:"))
        self.label_8.setText(_translate("MainWindow", "选择模型："))
        self.comboBox_5.setItemText(0, _translate("MainWindow", "UNet"))
        self.comboBox_5.setItemText(1, _translate("MainWindow", "VNet"))
        self.comboBox_5.setItemText(2, _translate("MainWindow", "U2Net"))
        self.cb_wwwc.setItemText(0, _translate("MainWindow", "纵隔窗"))
        self.cb_wwwc.setItemText(1, _translate("MainWindow", "肺窗"))
        self.cb_wwwc.setItemText(2, _translate("MainWindow", "软组织窗"))
        self.cb_wwwc.setItemText(3, _translate("MainWindow", "脑窗"))
        self.cb_wwwc.setItemText(4, _translate("MainWindow", "骨窗"))
        self.label_9.setText(_translate("MainWindow", "窗宽："))
        self.label_10.setText(_translate("MainWindow", "窗位："))
        self.label_11.setText(_translate("MainWindow", "病灶位置："))
        self.label_3.setText(_translate("MainWindow", "诊断步骤"))
        self.label_5.setText(_translate("MainWindow", "步骤一"))
        self.label_6.setText(_translate("MainWindow", "点击[加载模型]"))
        self.label_7.setText(_translate("MainWindow", "步骤二"))
        self.label_12.setText(_translate("MainWindow", "选择分类任务类别数量和模型种类"))
        self.label_13.setText(_translate("MainWindow", "步骤三"))
        self.label_14.setText(_translate("MainWindow", "点击[选择影像],选择要推理的CT图"))
        self.label_15.setText(_translate("MainWindow", "步骤四"))
        self.label_16.setText(_translate("MainWindow", "点击[开始推理]即可开始诊断"))
        self.label_17.setText(_translate("MainWindow", "步骤五"))
        self.label_18.setText(_translate("MainWindow", "点击[患者信息]，将该患者信息录\n"
"入系统中，以便生成诊断报告以及\n"
"后续查看"))
        self.label_19.setText(_translate("MainWindow", "步骤六"))
        self.label_20.setText(_translate("MainWindow", "点击[诊断报告]即可查看病历单"))
import three_rc
