# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1252, 800)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon/白色图标/订单.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(130, 40, 1022, 670))
        self.widget.setMinimumSize(QtCore.QSize(1022, 670))
        self.widget.setStyleSheet("#widget{\n"
"    background-color:rgb(17,17,19);\n"
"    border-radius:22px;\n"
"}")
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(self.widget)
        self.frame_2.setStyleSheet("#frame_2{\n"
"    background-color: rgb(16, 18, 31);\n"
"    border-radius:22px;\n"
"    \n"
"}\n"
"")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.frame = QtWidgets.QFrame(self.frame_2)
        self.frame.setGeometry(QtCore.QRect(0, 0, 1022, 48))
        self.frame.setStyleSheet("#frame{\n"
"    border-top-left-radius:22px;\n"
"    border-top-right-radius:22px;\n"
"    background-color:rgb(38,43,75);\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.frame)
        self.tabWidget_2.setGeometry(QtCore.QRect(930, 0, 91, 41))
        self.tabWidget_2.setStyleSheet("QTabBar::tab {\n"
"    font-size: 15px;\n"
"    margin-right: 3px;\n"
"    width: 80px;\n"
"    height: 30px;\n"
"    color:rgb(255, 255, 255);\n"
"    font-family:\"微软雅黑\" ;\n"
"    font-weight:bold;\n"
"}\n"
"\n"
"QTabWidget::pane {\n"
"    border: none;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    border-bottom: 2px solid transparent;\n"
"    padding: 4px;\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    border-color: #0072C6;\n"
"}\n"
"\n"
"")
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabWidget_2.addTab(self.tab_3, "")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(10, -20, 81, 81))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("icons/logo.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setGeometry(QtCore.QRect(390, 160, 261, 341))
        self.frame_3.setStyleSheet("#frame_3{\n"
"    border-radius:22px;\n"
"    background-color:rgb(28,34,56);\n"
"}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_4 = QtWidgets.QFrame(self.frame_3)
        self.frame_4.setStyleSheet("#frame_4{\n"
"    border-top-left-radius:22px;\n"
"    border-top-right-radius:22px;    \n"
"    background-color:rgb(38,43,75);\n"
"    \n"
"}")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label = QtWidgets.QLabel(self.frame_4)
        self.label.setGeometry(QtCore.QRect(10, 0, 51, 31))
        self.label.setStyleSheet("QLabel {\n"
"    font-size: 16px;\n"
"    font-family: \"微软雅黑\";\n"
"    font-weight: bold;\n"
"    color:white;\n"
"}")
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(self.frame_3)
        self.frame_5.setStyleSheet("#frame_5{\n"
"    border-bottom-left-radius:22px;\n"
"    border-bottom-right-radius:22px;    \n"
"    background-color: rgb(28,34,56);\n"
"    \n"
"}")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.tabWidget = QtWidgets.QTabWidget(self.frame_5)
        self.tabWidget.setGeometry(QtCore.QRect(0, 10, 261, 281))
        self.tabWidget.setStyleSheet("QTabBar::tab {\n"
"    font-size:16px;\n"
"    font-weight:bold;\n"
"    font-family:\"微软雅黑\";\n"
"    margin-right:10px;\n"
"    margin-left:10px;\n"
"    width: 40px;\n"
"    height: 40px;\n"
"    color:rgb(255, 255, 255);\n"
"    \n"
"}\n"
"QTabWidget::pane {\n"
"    border: none;\n"
"}\n"
"QTabBar::tab {\n"
"    border-bottom: 4px solid transparent;\n"
"    padding-right: 8px;\n"
"    margin-right: 10px;\n"
"}\n"
"QTabBar::tab:selected {\n"
"    border-color: #0072C6;\n"
"    color: rgb(0, 170, 255);\n"
"}\n"
"QTabWidget::tab-bar {\n"
"    alignment: center;\n"
"}\n"
"")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.frame_6 = QtWidgets.QFrame(self.tab)
        self.frame_6.setGeometry(QtCore.QRect(50, 0, 171, 211))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.layoutWidget = QtWidgets.QWidget(self.frame_6)
        self.layoutWidget.setGeometry(QtCore.QRect(1, 11, 171, 191))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.username1 = QtWidgets.QLineEdit(self.layoutWidget)
        self.username1.setStyleSheet("QLineEdit {\n"
"    color: rgb(206, 206, 206);\n"
"    height: 30px;\n"
"    border: 2px solid  #808080;\n"
"    background-color:transparent;\n"
"    font-weight:bold;\n"
"    font-family:\"微软雅黑\";\n"
"    font-size: 12px;\n"
"}")
        self.username1.setObjectName("username1")
        self.verticalLayout_3.addWidget(self.username1)
        self.password1 = QtWidgets.QLineEdit(self.layoutWidget)
        self.password1.setStyleSheet("QLineEdit {\n"
"    color: rgb(206, 206, 206);\n"
"    height: 30px;\n"
"    border: 2px solid  #808080;\n"
"    background-color:transparent;\n"
"    font-weight:bold;\n"
"    font-family:\"微软雅黑\";\n"
"    font-size: 12px;\n"
"}")
        self.password1.setText("")
        self.password1.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password1.setObjectName("password1")
        self.verticalLayout_3.addWidget(self.password1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.radioButton_2 = QtWidgets.QRadioButton(self.layoutWidget)
        self.radioButton_2.setStyleSheet("font-weight:bold;\n"
"    font-family:\"微软雅黑\";\n"
"    font-size: 12px;\n"
"color: rgb(206, 206, 206);")
        self.radioButton_2.setObjectName("radioButton_2")
        self.horizontalLayout_4.addWidget(self.radioButton_2)
        self.radioButton = QtWidgets.QRadioButton(self.layoutWidget)
        self.radioButton.setStyleSheet("font-weight:bold;\n"
"    font-family:\"微软雅黑\";\n"
"    font-size: 12px;\n"
"color: rgb(206, 206, 206);")
        self.radioButton.setObjectName("radioButton")
        self.horizontalLayout_4.addWidget(self.radioButton)
        self.horizontalLayout_4.setStretch(0, 2)
        self.horizontalLayout_4.setStretch(1, 1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton.setStyleSheet("QPushButton{\n"
"background-color:transparent;\n"
"font-size:12px;\n"
"font-family:\"微软雅黑\";\n"
"color:rgb(255,255, 255);\n"
"font-weight:bold;\n"
"}\n"
"QPushButton:hover {\n"
"background-color:transparent;\n"
"color:rgb(0, 170, 255);\n"
"transition: all 0.2s ease-in-out;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"font-size: 10px;\n"
"transition: all 0.2s ease-in-out;\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.frame_8 = QtWidgets.QFrame(self.layoutWidget)
        self.frame_8.setStyleSheet("")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.login_button = QtWidgets.QPushButton(self.frame_8)
        self.login_button.setGeometry(QtCore.QRect(0, 0, 169, 28))
        self.login_button.setStyleSheet("\n"
"QPushButton:pressed {\n"
"    border: 2px solid #333333;\n"
"    background-color: #BDBDBD; \n"
"    border-radius:12px\n"
"}\n"
"QPushButton{\n"
"    height:20px;\n"
"    \n"
"    \n"
"    color: rgb(57, 57, 57);\n"
"    font-size:16px;\n"
"    font-family:\"微软雅黑\";\n"
"    font-weight:bold;\n"
"}")
        self.login_button.setObjectName("login_button")
        self.verticalLayout_3.addWidget(self.frame_8)
        self.verticalLayout_3.setStretch(1, 1)
        self.verticalLayout_3.setStretch(3, 1)
        self.verticalLayout_3.setStretch(4, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.frame_7 = QtWidgets.QFrame(self.tab_2)
        self.frame_7.setGeometry(QtCore.QRect(50, -20, 171, 241))
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.layoutWidget_2 = QtWidgets.QWidget(self.frame_7)
        self.layoutWidget_2.setGeometry(QtCore.QRect(0, 30, 171, 210))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.lineEdit_4.setStyleSheet("QLineEdit {\n"
"    color: rgb(206, 206, 206);\n"
"    height: 30px;\n"
"    border: 2px solid  #808080;\n"
"    background-color:transparent;\n"
"    font-weight:bold;\n"
"    font-family:\"微软雅黑\";\n"
"    font-size: 12px;\n"
"}")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.verticalLayout_4.addWidget(self.lineEdit_4)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.lineEdit_5.setStyleSheet("QLineEdit {\n"
"    color: rgb(206, 206, 206);\n"
"    height: 30px;\n"
"    border: 2px solid  #808080;\n"
"    background-color:transparent;\n"
"    font-weight:bold;\n"
"    font-family:\"微软雅黑\";\n"
"    font-size: 12px;\n"
"}")
        self.lineEdit_5.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.verticalLayout_4.addWidget(self.lineEdit_5)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.lineEdit_6.setStyleSheet("QLineEdit {\n"
"    color: rgb(206, 206, 206);\n"
"    height: 30px;\n"
"    border: 2px solid  #808080;\n"
"    background-color:transparent;\n"
"    font-weight:bold;\n"
"    font-family:\"微软雅黑\";\n"
"    font-size: 12px;\n"
"}")
        self.lineEdit_6.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.verticalLayout_4.addWidget(self.lineEdit_6)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.radioButton_3 = QtWidgets.QRadioButton(self.layoutWidget_2)
        self.radioButton_3.setStyleSheet("font-weight:bold;\n"
"    font-family:\"微软雅黑\";\n"
"    font-size: 12px;\n"
"color: rgb(206, 206, 206);")
        self.radioButton_3.setObjectName("radioButton_3")
        self.horizontalLayout_5.addWidget(self.radioButton_3)
        self.radioButton_4 = QtWidgets.QRadioButton(self.layoutWidget_2)
        self.radioButton_4.setStyleSheet("font-weight:bold;\n"
"    font-family:\"微软雅黑\";\n"
"    font-size: 12px;\n"
"color: rgb(206, 206, 206);")
        self.radioButton_4.setObjectName("radioButton_4")
        self.horizontalLayout_5.addWidget(self.radioButton_4)
        self.horizontalLayout_5.setStretch(0, 2)
        self.horizontalLayout_5.setStretch(1, 1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.pushButton_4 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton_4.setStyleSheet("QPushButton{\n"
"background-color:transparent;\n"
"font-size:12px;\n"
"font-family:\"微软雅黑\";\n"
"    color: rgb(213, 213, 213);\n"
"font-weight:bold;\n"
"}\n"
"QPushButton:hover {\n"
"background-color:transparent;\n"
"color:rgb(0, 170, 255);\n"
"transition: all 0.2s ease-in-out;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"font-size: 10px;\n"
"transition: all 0.2s ease-in-out;\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_3.addWidget(self.pushButton_4)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.pushButton_5 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton_5.setStyleSheet("\n"
"QPushButton:pressed {\n"
"    border: 2px solid #333333;\n"
"    background-color: #BDBDBD; \n"
"    border-radius:12px\n"
"}\n"
"QPushButton{\n"
"    height:20px;\n"
"    \n"
"    \n"
"    color: rgb(57, 57, 57);\n"
"    font-size:16px;\n"
"    font-family:\"微软雅黑\";\n"
"    font-weight:bold;\n"
"}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_4.addWidget(self.pushButton_5)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout_2.addWidget(self.frame_5)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 8)
        self.verticalLayout.addWidget(self.frame_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget_2.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), _translate("MainWindow", "登录"))
        self.label.setText(_translate("MainWindow", "登录"))
        self.username1.setPlaceholderText(_translate("MainWindow", "请输入姓名"))
        self.password1.setPlaceholderText(_translate("MainWindow", "请输入工号/ID号"))
        self.radioButton_2.setText(_translate("MainWindow", "医生"))
        self.radioButton.setText(_translate("MainWindow", "患者"))
        self.pushButton.setText(_translate("MainWindow", "登录遇到问题？"))
        self.login_button.setText(_translate("MainWindow", "登录"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "登录"))
        self.lineEdit_4.setPlaceholderText(_translate("MainWindow", "请输入姓名"))
        self.lineEdit_5.setPlaceholderText(_translate("MainWindow", "请输入工号/ID号"))
        self.lineEdit_6.setPlaceholderText(_translate("MainWindow", "请确认工号/ID号"))
        self.radioButton_3.setText(_translate("MainWindow", "医生"))
        self.radioButton_4.setText(_translate("MainWindow", "患者"))
        self.pushButton_4.setText(_translate("MainWindow", "注册遇到问题？"))
        self.pushButton_5.setText(_translate("MainWindow", "注册"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "注册"))
